services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    # si tu veux exécuter les scripts init en prod aussi :
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../../DB/init-db:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

  frontend:
    image: ghcr.io/${GHCR_OWNER}/auto_thesis-frontend:${APP_VERSION}
    restart: unless-stopped
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:3000"

volumes:
  pg_data:
  redis_data:
